---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: secure-app
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: secure-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/Conclusion-Xforce/container-security.git
    contextDir: 01-container
    dockerfile: |
      FROM nginx:1.19.6-alpine
      <PASTE YOUR DOCKERFILE HERE>
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: secure-app:latest
---
